export default Object.freeze({
    GET_POSTS: 'posts/GET_POSTS',
    GET_POSTS_FULFILLED: 'posts/GET_POSTS_FULFILLED',
    GET_POSTS_REJECTED: 'posts/GET_POSTS_REJECTED',

    GET_POST: 'posts/GET_POST',
    GET_POST_FULFILLED: 'posts/GET_POST_FULFILLED',
    GET_POST_REJECTED: 'posts/GET_POST_REJECTED',

    EDIT_POST: 'posts/EDIT_POST',
    EDIT_POST_FULFILLED: 'posts/EDIT_POST_FULFILLED',
    EDIT_POST_REJECTED: 'posts/EDIT_POST_REJECTED',

    DELETE_POST: 'posts/DELETE_POST',
    DELETE_POST_FULFILLED: 'posts/DELETE_POST_FULFILLED',
    DELETE_POST_REJECTED: 'posts/DELETE_POST_REJECTED',
    
    CREATE_POST: 'posts/CREATE_POST',
    CREATE_POST_FULFILLED: 'posts/CREATE_POST_FULFILLED',
    CREATE_POST_REJECTED: 'posts/CREATE_POST_REJECTED'
})